rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true